### ISSUE TITLE
goreleaser: package sample config

### ISSUE THREAD

**Issue by geigi** [sipgate/gnt-cc#23]
Example:
```yaml
    # Config files to add to your package. They are about the same as
    # the files keyword, except package managers treat them differently (while
    # uninstalling, mostly).
    # Keys are source paths/globs to get the files from.
    # Values are the destination locations of the files in the package.
    config_files:
      "tmp/app_generated.conf": "/etc/app.conf"
      "conf/*.conf": "/etc/foo/"
```
